reddit:
  client_id: "w1Fdkahc9dZaJsMDkpcL9A"
  client_secret: "K7kyRGo2IjgEdXBtHT8XMBseA2JK8g"

google:
  custom_search_id: "f1779ac0cca734715"
  api_key: "AIzaSyBQM0GbvWop5PqCWxk8DQg40-Ww3vKRvMQ"

pexels: "eojCgUA62sseU7z73cAwbZQc3BoZLH6bRFiEoEcezLH6N8HpR017eLVR"
